################################################################################
# Lab 30 Outputs — EFS and FSx
################################################################################

output "efs_id" {
  description = <<-EOT
    EFS file system ID.
    Mount command (with TLS encryption in transit — required by the file system policy):
      sudo mount -t efs -o tls ${aws_efs_file_system.main.id}:/ /mnt/efs
    Or with an access point:
      sudo mount -t efs -o tls,accesspoint=<access_point_id> ${aws_efs_file_system.main.id}:/ /mnt/efs
    SAA-C03: Always use -o tls when the file system policy enforces SecureTransport.
  EOT
  value       = aws_efs_file_system.main.id
}

output "efs_dns_name" {
  description = <<-EOT
    EFS DNS name for mounting — resolves to the mount target IP in the requesting EC2's AZ.
    Format: <file-system-id>.efs.<region>.amazonaws.com
    SAA-C03: The same DNS name works from any AZ. Route 53 returns the AZ-local
    mount target IP, keeping NFS traffic within the AZ to minimize latency and cost.
  EOT
  value       = aws_efs_file_system.main.dns_name
}

output "efs_access_point_id" {
  description = <<-EOT
    EFS access point ID for app1.
    Use this in:
      - Lambda: aws_lambda_function file_system_config.arn (access point ARN)
      - ECS task definition: efsVolumeConfiguration.authorizationConfig.accessPointId
      - Direct mount: sudo mount -t efs -o tls,accesspoint=<id> <fs-id>:/ /mnt
    SAA-C03: Access points enforce UID/GID 1001 and restrict root to /app1/data.
  EOT
  value       = aws_efs_access_point.app1.id
}

output "efs_access_point_lambda_id" {
  description = <<-EOT
    EFS access point ID for Lambda functions.
    Lambda REQUIRES an access point to mount EFS — raw file system mounts are not supported.
    Configure in aws_lambda_function: file_system_config { arn = aws_efs_access_point.lambda.arn }
  EOT
  value       = aws_efs_access_point.lambda.id
}

output "efs_kms_key_arn" {
  description = <<-EOT
    ARN of the KMS CMK used for EFS encryption at rest.
    SAA-C03: Using a CMK (vs the default aws/elasticfilesystem key) enables:
      - Custom key rotation policies
      - Key disabling and scheduled deletion
      - Cross-account key grants
      - Detailed key usage auditing in CloudTrail
  EOT
  value       = aws_kms_key.efs.arn
}

output "fsx_lustre_id" {
  description = <<-EOT
    FSx for Lustre file system ID.
    Mount command from a Linux EC2 (requires lustre-client kernel module):
      sudo mount -t lustre -o noatime,flock \
        ${aws_fsx_lustre_file_system.hpc.dns_name}@tcp:/${aws_fsx_lustre_file_system.hpc.mount_name} \
        /mnt/lustre
    SAA-C03: Lustre clients must be Linux; Windows is not supported.
  EOT
  value       = aws_fsx_lustre_file_system.hpc.id
}

output "fsx_lustre_dns_name" {
  description = <<-EOT
    FSx for Lustre DNS name used in the mount command.
    Format: <fs-id>.fsx.<region>.amazonaws.com
    SAA-C03: FSx Lustre is single-AZ; this DNS resolves to a single endpoint
    (unlike EFS which resolves to AZ-local mount targets).
  EOT
  value       = aws_fsx_lustre_file_system.hpc.dns_name
}

output "fsx_lustre_mount_name" {
  description = <<-EOT
    FSx for Lustre mount name — used as the path component after @tcp:/ in the mount command.
    Example: mount -t lustre <dns>@tcp:/<mount_name> /mnt/lustre
    This value is auto-generated by AWS and unique per file system.
  EOT
  value       = aws_fsx_lustre_file_system.hpc.mount_name
}

output "fsx_lustre_s3_repository_bucket" {
  description = <<-EOT
    S3 bucket linked as the data repository for the FSx Lustre file system.
    Input data:  s3://${aws_s3_bucket.lustre_data.bucket}/input/
    Output data: s3://${aws_s3_bucket.lustre_data.bucket}/output/
    SAA-C03: Files in the input/ prefix appear in Lustre namespace immediately.
    They are fetched from S3 only on first access (lazy loading — no upfront copy).
  EOT
  value       = aws_s3_bucket.lustre_data.bucket
}

output "exam_cheat_sheet" {
  description = "SAA-C03 quick reference for file storage service selection"
  value       = <<-EOT
    SAA-C03 FILE STORAGE DECISION GUIDE:
    ─────────────────────────────────────────────────────────────
    EFS:  NFS v4.1, Linux/POSIX, multi-AZ, elastic storage, TCP 2049
          Performance: generalPurpose (low latency) or maxIO (massively parallel)
          Throughput:  bursting | provisioned | elastic
          Storage:     Standard | IA (lifecycle policy moves files after N days)
          Access Points: enforce root dir + UID/GID; REQUIRED for Lambda

    FSx Lustre: Parallel FS, Linux only, single-AZ, HPC/ML
          Deployment: SCRATCH_2 (temp, no replication) | PERSISTENT_2 (durable, SSD)
          S3 repo: lazy load from S3 on first access; export back to S3
          Ports: TCP 988 + 1018-1023

    FSx Windows: SMB, Windows only, Active Directory REQUIRED
          Deployment: SINGLE_AZ_2 | MULTI_AZ_1 (HA, ~30s failover)
          Features: NTFS ACLs, DFS namespaces, Shadow Copies (VSS)
          Port: TCP 445

    FSx NetApp ONTAP: NFS + SMB + iSCSI simultaneously, lift-and-shift NetApp
    FSx OpenZFS:      ZFS snapshots + clones, NFS, lift-and-shift ZFS
    Storage Gateway:  Hybrid; File (NFS/SMB→S3) | Volume (iSCSI→EBS) | Tape (VTL→Glacier)
    ─────────────────────────────────────────────────────────────
    Encryption at rest: kms_key_id = CMK ARN (more control vs aws/elasticfilesystem)
    Encryption in transit: mount -o tls (EFS) | enforced by file system policy
    ─────────────────────────────────────────────────────────────
  EOT
}
